v0.1
tsanyqudsi/menu-simple-kit pull request #1
Opened 2023-08-02 13:52 UTC by ahsan2607

2023-08-02 13:52 UTC, ahsan2607 commented
kang minta akses untuk bisa update

2023-08-03 12:02 UTC, tsanyqudsi requested changes
Lo pake Visual Studio Code kan ? Install Prettier sama Eslint untuk VSCode. Tabnya biasakan 2 kecuali XML kalo ga nanti kepanjangan dan ga rapih.

Terus kayanya gue ga taro prettier sama eslint deh. Lo coba install dan apply.

2023-08-03 12:02 UTC, tsanyqudsi commented on workspaces/msk/src/components/menus/MenuElement.tsx
> +// import { Link } from 'react-router-dom';
Ini Kenapa dicomment ?

2023-08-03 12:02 UTC, tsanyqudsi commented on workspaces/msk/src/components/displays/Footer.tsx
> +	return <Box height="100px"></Box>;
pake sx aja jgn langsung height biar konsisten sama yang lain

2023-08-03 12:02 UTC, tsanyqudsi commented on workspaces/msk/src/components/menus/MenuList.tsx
> +		<Grid container spacing={3} sx={{ padding: '0 20px 0 20px' }}>
seinget gue spacing bisa ditaro di sx deh.. cuma coba cek lagi.

2023-08-03 12:02 UTC, tsanyqudsi commented on workspaces/msk/src/layouts/Base.tsx
> +			<Hero backgroundColor="rgb(80,0,40)" />
pake sx

2023-08-03 12:02 UTC, tsanyqudsi commented on workspaces/msk/src/main.tsx
> +import { ThemeProvider } from '@mui/material/styles';
biasakan kl dari package itu ditaro di atas. Ga ngaruh sih, cuma jadi lebih terorganisir.

2023-08-04 02:14 UTC, ahsan2607 commented on workspaces/msk/src/components/menus/MenuElement.tsx
> +// import { Link } from 'react-router-dom';
dimatiin sementara kang, soalnya blum dipke buat skrg. Kata kang joo

2023-08-04 02:47 UTC, ahsan2607 commented on workspaces/msk/src/layouts/Base.tsx
> +			<Hero backgroundColor="rgb(80,0,40)" />
Type '{ sx: { bgcolor: string; }; }' is not assignable to type 'IntrinsicAttributes & HeroProps'.
  Property 'sx' does not exist on type 'IntrinsicAttributes & HeroProps'.

  ada error gtu, aku pke props backgroundColor dri component Hero

2023-08-04 03:01 UTC, tsanyqudsi commented on workspaces/msk/src/components/menus/MenuElement.tsx
> +// import { Link } from 'react-router-dom';
I see.. ini kan template. Jd mending buat opsi untuk nyalain / matiin.

2023-08-04 03:01 UTC, ahsan2607 commented on workspaces/msk/src/layouts/Base.tsx
> +			<Hero backgroundColor="rgb(80,0,40)" />
btw cara import footer gmn kang

"Module '"@components"' has no exported member 'Footer'."

gtu soalnya

2023-08-04 03:03 UTC, merged